Resp fix
SrushtiSalvi/glc pull request #1
Opened 2022-01-16 12:48 UTC by SrushtiSalvi

2022-01-16 13:00 UTC, SrushtiSalvi commented
![image](https://user-images.githubusercontent.com/69090087/149660967-f588f2a0-77cd-4950-a387-24bcab95cca8.png)

2022-01-17 06:39 UTC, StandinKP requested changes

2022-01-17 08:33 UTC, SrushtiSalvi commented on src/components/PhotoCarousel.js
> +      <section className="border-1 relative h-200">
done

2022-01-17 08:38 UTC, SrushtiSalvi commented on src/components/PostCard.js
> +    <div className="px-6 pt-6 m-3 shadow-md shadow-gray-400 bg-white">
done

2022-01-17 12:37 UTC, merged